### ISSUE TITLE
Vector Database Feasibility On-Device

### ISSUE THREAD

**Issue by thomasjv799** [ImadSaddik/DocChat#2]
Hi
I just wanna know if you are storing the embeddings in sqlite or other vector DB. Also how feasible is the DB when we have large contents say more than 500 pages. 
In addition is there a possiblilty to add [ObjectBox](https://objectbox.io/) or other vector DB such as Qdrant by trying to build an android  version.

**Comment by ImadSaddik** [comment]
Hello @thomasjv799

Yes, I am storing the embeddings in a SQLite database. In Python, there exists a lot of vector DBs, but in Java I was not aware of anything. This is why I choose to build my own vector DB, and it was a lot of fun.

For big documents, first you need to use the paid version of the Gemini API since it will take forever to embed it with the free API. I can't give you an answer about if the database can handle very large documents, but I think it can handle them.

I never heard about ObjectBox before, thanks for sharing it with me. I think you can use it without any problems, just drop the SQLite database and replace it with any other DB.

Hope that this answers your quetions.

**Comment by thomasjv799** [comment]
Thanks, I will experiment and see.
